### ISSUE TITLE
On update remote plugins 

### ISSUE THREAD

**Issue by zamaterian** [clojure-vim/acid.nvim#13]
Do you have any suggestions ? 

Encountered SyntaxError loading plugin at /home/te/.vim/plugged/acid.nvim/rplugin/python3/acid: can use starred expression only as assignment target (__init__.
py, line 99)                                                                                                                                                   
Traceback (most recent call last):                                                                                                                             
  File "/home/te/.local/lib/python3.4/site-packages/neovim/plugin/host.py", line 131, in _load                                                                 
    module = imp.load_module(name, file, pathname, descr)                                                                                                      
  File "/usr/lib/python3.4/imp.py", line 245, in load_module                                                                                                   
    return load_package(name, filename)                                                                                                                        
  File "/usr/lib/python3.4/imp.py", line 217, in load_package                                                                                                  
    return methods.load()                                                                                                                                      
  File "<frozen importlib._bootstrap>", line 1220, in load                                                                                                     
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked                                                                                           
  File "/home/te/.vim/plugged/acid.nvim/rplugin/python3/acid/__init__.py", line 99                                                                             
    *handlers, self.get_handler('Log').configure(**self.context())                                                                                             
                   ^                                                                                                                                           
SyntaxError: can use starred expression only as assignment target                                                                                              
remote/host: python3 host registered plugins []                                                                                                                
remote/host: generated rplugin manifest: /home/te/.local/share/nvim/rplugin.vim

**Comment by SevereOverfl0w** [comment]
Acid possibly depends on newer features/syntax than is present in python3.4. Without having figured out what that line is doing (generators maybe?) I can reccomend trying to update first if that's possible.

**Comment by hkupty** [comment]
My bet is that the `*handlers, ..` destructuring syntax inside the generator might be breaking in python 3.4.

If bumping python to 3.5+ is a problem, I'll try to rewrite it in a 3.0+ compatible way, instead of 3.5+.

**Comment by zamaterian** [comment]
thx I will upgrade my python :)
