### ISSUE TITLE
Commands are not working

### ISSUE THREAD

**Issue by danieltdt** [clojure-vim/acid.nvim#21]
I'm trying to load documentation (using `K`) but a error is raised.

I followed the install steps on README, I don't know what I am missing :(

```
error caught while executing async callback:                                                                                                                                                                        
KeyError('name',)
Traceback (most recent call last):
  File "/home/daniel/.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/handlers/__init__.py", line 78, in <lambda>                                                                                           
    nvim.async_call(lambda: on_handle(msg, wc, key))
  File "/home/daniel/.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/handlers/doc.py", line 17, in on_handle                                                                                               
    name = msg['name']
KeyError: 'name'
 
the call was requested at
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "../../.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/nrepl/__init__.py", line 68, in run                                                                                                          
    callback(incoming, self, key)
  File "/home/daniel/.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/handlers/__init__.py", line 78, in handler                                                                                            
    nvim.async_call(lambda: on_handle(msg, wc, key))
Press ENTER or type command to continue
```

**Comment by hkupty** [comment]
Hi, thanks for the issue.

From the error you're gettiThis can be fixed by ng, I'd guess that this is caused by the file not being loaded on the nrepl.

This is strange and needs some investigation, because acid would normally auto require the file.

Are the other commands working? Can you run `gd` on a symbol and go to it?

Also, I know that the project is probably private, but can you reproduce it on a public project so I can test it as well?

Thanks in advance,
Henry John Kupty

**Comment by danieltdt** [comment]
The `gd` does nothing (not even an error message).

I'll try on a public project and post here again. But for the record, the `msg` is a dict as
```
{'id': 'c096be2616374bc8951ebcce961b0626', 'op': 'info', 'session': 'f6f024fd-71c0-4491-8bf1-f83c8bd59fcf', 'status': ['done', 'unknown-op', 'error']}
```

**Comment by hkupty** [comment]
`unknown-op` hum.. could be that you're missing either `refactor-nrepl` or `cider-nrepl` middlewares.

It'd probably be better to implement a catch for that.

Did you successfully install those?

**Comment by danieltdt** [comment]
I've added to `~/.lein/profiles.clj` and ran `lein deps` before `lein repl`.
Should I configure the acid.vim to start the repl rather than I start by myself?

**Comment by danieltdt** [comment]
I found my mistake :sweat_smile: I was starting `lein repl` using my project profile, and the `~/.lein/profiles.clj` were being ignored. The only thing I had to change is update `refactor-nrepl` to 2.3.1 and `cider/cider-nrepl` to 0.15.1

Thank you for the help :heart:

**Comment by hkupty** [comment]
Great! Glad I could help!

Cheers,
Henry John Kupty
