### ISSUE TITLE
:AcidRequire clojure.string - Weird error

### ISSUE THREAD

**Issue by aterribili** [clojure-vim/acid.nvim#52]
Not sure if I did something wrong on setup, but when trying to execute `:AcidRequire clojure.string` I'm getting the following error:
```
error caught in async handler '/Users/aterribili/.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid:function:AcidSendNrepl [[{'code': "(find-ns 'async-clj-highlight)", 'op': 'eval', 'id': '4200af14832b448181b47732df563405'}, 'VimFn'
, 'AsyncCljHighlightPrepare']]'
Traceback (most recent call last):
  File "/Users/aterribili/.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/__init__.py", line 82, in acid_eval
    success, msg = send(self.session_handler, url, [handler], payload)
  File "/Users/aterribili/.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/session.py", line 74, in send
    session.add_atomic_watch(url, msg_id, handler, matcher)
  File "/Users/aterribili/.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/session.py", line 43, in add_atomic_watch
    conn = self.get_or_create(url)
  File "/Users/aterribili/.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/session.py", line 27, in get_or_create
    conn = nrepl.connect(url)
  File "../../.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/nrepl/__init__.py", line 129, in connect
    return f(uri)
  File "../../.local/share/nvim/plugged/acid.nvim/rplugin/python3/acid/nrepl/__init__.py", line 31, in _bencode_connect
    s = socket.create_connection(uri.netloc.split(":"))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by hkupty** [comment]
This error is related with async-clj-highlight, apparently. It is not working with the lua version. I'm working on a fix for that which should be available soon.

Sorry for the inconvenience.

**Comment by hkupty** [comment]
Meanwhile, disabling async-clj-highlight should fix this issue.

**Comment by aterribili** [comment]
dahora!

**Comment by hkupty** [comment]
Do you care to check if clojure-vim/async-clj-highlight#2 works for you? I'm trying locally and works for me, but I might have some edge case I'm not seeing.

Cheers,
Henry

**Comment by hkupty** [comment]
I believe this one is fixed now. I'll close it, but please reopen if you still have problems.

Best,
Henry
